// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NBKVSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "NBKVSExtension.dda41313-dfbc-48f4-863d-49b19dcd1302";
        public const string Name = "NBKVSExtension";
        public const string Description = @"Visual Studio Extension used for project management.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "NBK";
        public const string Tags = "";
    }
}
