// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NBKVSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NBKVSExtensionString = "c81f8805-b10c-4645-8bcb-2ec5d9319c62";
        public static Guid NBKVSExtension = new Guid(NBKVSExtensionString);

        public const string guidNBKVSExtensionGroupSetString = "b773fe54-333c-4931-97eb-c6aa79aeca00";
        public static Guid guidNBKVSExtensionGroupSet = new Guid(guidNBKVSExtensionGroupSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopLevelMenu = 0x1022;
        public const int InternalReferenceGroup = 0x1023;
    }
}